config/urls.py
from django.contrib import admin
from django.urls import include, path
from config.views import main_home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_home, name='home'),
    path('', include('images.urls', namespace='images')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from config.views import generate_image_to_text

# create namapspace
app_name = 'images'

urlpatterns = [
    path('generate-image', generate_image_to_text, name='generate'),
]

images/models.py
from django.db import models

# Create your models here.


class Images(models.Model):
    phrase = models.CharField(max_length=200)
    ai_image = models.ImageField(upload_to='media')

    def __str__(self):
        return str(self.phrase)

config/views.py
from django.shortcuts import render
import openai
import os
import requests
from dotenv import load_dotenv
from django.core.files.base import ContentFile
from images.models import Images
load_dotenv()

api_key = os.getenv('OPENAI_KEY', None)
openai.api_key = api_key


def generate_image_to_text(request):
    obj = None
    if api_key is not None and request.method == 'POST':
        user_input = request.POST.get('user_input')
        response = openai.Image.create(
            prompt=user_input,
            size='256x256'  # 256x256, 512x512, and 1024x1024

        )
        print("before response")
        print(response)
        img_url = response["data"][0]["url"]
        response = requests.get(img_url)
        print(response)  # <Response [200]>
        img_file = ContentFile(response.content)

        count = Images.objects.count() + 1
        fname = f"image-{count}.jpg"

        obj = Images(phrase=user_input)
        obj.ai_image.save(fname, img_file)
        obj.save()
        print("before object print")
        print(obj)

    context = dict(
        object=obj,
    )
    return render(request, "main.html", context)


def main_home(request):
    return render(request, 'home.html')

images/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Generate Image</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
  </head>
  <body>
    
    <div class="container mt-3">{% block content %} {% endblock content %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
  <h1>Home</h1>
  <p>Welcome to the home page</p>
  <a href="{% url 'images:generate' %}" class="btn btn-primary">Generate Image</a>
{% endblock content %}
```

templates/main.html
{% extends 'base.html' %} {% block content %}
<h3>Write an instruction to generate image</h3>

<form method="post">
  {% csrf_token %}
  <input
    type="text"
    class="form-control"
    name="user_input"
    placeholder="Enter a prompt"
  /><br /><br />
  <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

{% if object %}
<div>
  {{ object.phrase }}
  <br />
  <img src="{{ object.ai_image.url }}" alt="{{ object.phrase }}" />
</div>
{% endif %} 
{% endblock content %}